apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    web: apache
    app: tomcat
spec:
  initContainers:
    - name: alpine
      image: alpine:3.18.2
      args:
        - sleep
        - 10s
    - name: alpine1
      image: alpine:3.17.4
      args:
        - sleep
        - 11s        
  restartPolicy: OnFailure
  containers:
    - name: httpd
      image: httpd:2.4.57
      ports:
        - name: httpd-port
          protocol: TCP
          containerPort: 80
    - name: tomcat
      image: tomcat:11.0.0-M7-jdk21-openjdk-bookworm
      ports:
        - name: tomcat-port
          protocol: TCP
          containerPort: 8080
