apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels: 
    app: nginx
spec:
  minReadySeconds: 2
  replicas: 8
  selector:
    matchLabels:
      app: nginx 
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50% 
    type: RollingUpdate
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:   
      containers:
        - image: nginx:1.23 
          name: nginx
          ports:
            - containerPort: 80
              name: nginx-port
              protocol: TCP