apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx   
  ports:
    - name: nginx-port
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer    
  