---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: horizontal
  labels:
    app: nginx
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    name: login-deployment
    kind: Deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageUtilization: 1
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageUtilization: 1
