---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
  labels:
    vol: pvc
spec:
  selector:
    matchLabels:
      app: nginx
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi 
  accessModes: 
    - ReadWriteOnce  
