apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 4
  selector: 
    matchLabels: 
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        ver: "1.0"    
    spec: 
      containers:
        - name: nginx-container
          image: nginx:1.23
          ports:
            - name: nginx-port
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: sample-volume
      volumes:
        - name: sample-volume
          persistentVolumeClaim:
            claimName: test-volume
      initContainers:
        - name: alpine
          image: alpine:3.18.2
          args:
            - sleep
            - 10s  
        - name: alpine1
          image: alpine:3.17.4
          args: 
            - sleep
            - 15s 