apiVersion: v1
kind: Service
metadata:
  name: spc-svc
  labels:
    app: spc
spec:
  type: LoadBalancer
  selector: 
    app: spc
  ports:
    - name: spc-port
      port: 8080
      targetPort: 8080
      protocol: TCP