apiVersion: batch/v1
kind: CronJob
metadata: 
  name: cron-based
  labels: 
    app: nginx 
spec:
  schedule: "* * * * *"
  jobTemplate: 
    metadata:
      name: cronjob
      labels: 
        component: web
    spec:
      selector:
        # matchExpressions:
        #   - key: app
        #     operator: In
        #     values:
        #       - nginx
        #       - web
        matchlabels: 
          component: web  
      template:
        metadata:
          name: nginx
          labels:
            component: web
        spec:
          restartPolicy: Never
          containers:
            - image: nginx:1.23
              name: nginx
              ports:
                - containerPort: 80
                  name: port
                  protocol: TCP   