apiVersion: apps/v1
kind: Deployment
metadata: 
  name: order
spec:
  minReadySeconds: 2
  replicas: 3
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      name: order 
      labels:
        app: order
        version: 1.0
    spec:
      containers:
        - name: order-container 
          image: 
          readinessProbe:
            exec: 
            failureThreshold:
          livenessProbe:
            exec:
            failureThreshold:
          startupProbe:
            exec:
            failureThreshold:
          resources:            
            requests: 
              memory: "64Mi"
              cpu: "250m"
            limits:     
              memory: "128Mi"
              cpu: "500m"  
          ports:
            - containerPort: 80
              name: order-port
              protocol: TCP
