apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels: 
    app: apache
spec: 
  type: ClusterIP
  ports:
    - name: service-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    application: apache
    
           