apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dashboard
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: dashboard-board
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard-container
          image: shaikkhajaibrahim/dashboardservice:1.0.0
          ports:
            - containerPort: 80
              name: dash-port
              protocol: TCP
                    
