apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc
spec:
  ports:
    - name: dashboard-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dashboard
  type: LoadBalancer      
   
